### ISSUE TITLE
Is there any way to make this project work with Flipper Zero?

### ISSUE THREAD

**Issue by HonzaaD** [Rafisto/led-control#4]
Hi Rafista, interesting project. 

I'm wondering if this code can somehow be used and implemented in Flipper Zero so that this device can then be used to control MiBoxer lights? Is that possible? Do you happen to have any experience with Flipper Zero? 

Thank you very much in advance for the answer.

**Comment by Rafisto** [comment]
Hey, I believe it is possible with any modern device capable of communicating on 2.4GHz.

This repository is just a web interface for what has been beautifully achieved at the lower level by the author of this article:
- https://hackaday.io/project/5888-reverse-engineering-the-milight-on-air-protocol

There exists a repository with an in-depth instruction on how to integrate MiBoxer drivers using ESP8266:
- https://github.com/sidoh/esp8266_milight_hub

Hope these resources will be helpful to you and your project.
Have a nice day :)

**Comment by Rafisto** [comment]
I unfortunately don't have a flipper zero to help you out.

**Comment by HonzaaD** [comment]
Thank you very much, I'll study the resources... It'll get me somewhere again.
